In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets 

In [2]:
iris = datasets.load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [5]:
X = iris.data

In [6]:
X.shape

(150, 4)

In [7]:
y = iris.target

In [8]:
y.shape

(150,)

## train_test_split
分离出一部分数据做训练，另外一部分数据做测试。

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
shuffled_indexes = np.random.permutation(len(X))
shuffled_indexes

array([ 36,  31,  99,  20,  55,  61,   9,  76, 130,   1, 108, 120,  42,
        11, 109,  60, 149,  86, 118, 123,  22,  48,  10,   7,  34,  54,
       101,  30,  26, 114, 127,  67,  12,  40,  79, 115,  68,  15, 146,
       136, 112,  41,  73, 137, 139,   2,  89,  27,  59, 133,  62,  95,
        23,  91,  84, 138,   4, 102,  97,  18, 116,  24,  32,  63,  65,
         6, 111, 117,  88,  56,  39,  70,  92,  47,  57,  98,  21, 113,
         8,  16,  38,  19, 148,  77,  46,  87,  51, 142,  44, 143, 122,
        78, 121,   0,   3,  49,  96,  25, 104,  74,  81,  58, 135,  43,
       128,  82,  45, 132,  72, 134,  14,  52, 144, 141,  64, 145,  35,
       126,  53, 110,  80, 129, 131,  37, 107, 125,  94,  71, 106, 119,
        50,  66,  13,  17,  29,  90, 100, 124,  83, 147,  85,  33, 103,
        28,   5, 105,  75, 140,  69,  93])

In [13]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [14]:
test_indexes = shuffled_indexes[:test_size]
train_indexes = shuffled_indexes[test_size:]

In [16]:
X_train = X[train_indexes]
y_train = y[train_indexes]

y_test = X[test_indexes]
y_test = y[test_indexes] 

In [17]:
print(X_train.shape)
print(y_test.shape)

(120, 4)
(30,)


### 封装

In [18]:
from playML.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [19]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [20]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


### 测试自己的算法

In [22]:
from playML.kNN import KNNClassifier

my_knn_clf = KNNClassifier(k=3)
my_knn_clf.fit(X_train, y_train)
y_predict = my_knn_clf.predict(X_test)

In [23]:
y_predict

array([1, 0, 1, 1, 0, 2, 2, 1, 1, 0, 2, 2, 2, 1, 1, 2, 1, 2, 0, 0, 0, 2,
       2, 2, 0, 2, 1, 2, 0, 2])

In [24]:
y_test

array([1, 0, 1, 1, 0, 2, 2, 1, 1, 0, 2, 2, 2, 1, 1, 2, 1, 2, 0, 0, 0, 2,
       2, 1, 0, 2, 1, 1, 0, 2])

In [25]:
sum(y_predict == y_test)

28

In [26]:
sum(y_predict == y_test) / len(y_test)

0.9333333333333333