## 测试我们自己的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets 

In [3]:
iris = datasets.load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [3]:
X = iris.data

In [4]:
y = iris.target

In [5]:
X.shape

(150, 4)

In [6]:
y.shape

(150,)

### train_test_split

分离出一部分数据做训练，另外一部分数据做测试。

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
shuffled_indexes = np.random.permutation(len(X))
shuffled_indexes   

array([114,  52,  74,  88,  63, 141,  48,  57,   3,  23,  35,   8, 119,
        97,  87,  28, 104,  68,   0,  36, 120,  44,  66, 121,  75,   2,
       117, 100,  30,  82, 128,  18, 106,  22, 130, 109,  90,  70,  92,
        98,  67, 138,  17, 124, 115,  10,  72, 134, 140, 135,  25, 143,
        91,  43,  38, 101,  15,  13, 123, 137, 116,  65, 108,  33, 142,
         6,  11, 136,  45,  93, 147,  27,  89,  20,  58,  40,  80, 118,
        56, 103,   1,  42, 107,  61,  51, 139,  53, 126, 148,  37,  24,
        99,  83,  55,  76,  29,  94, 131, 110,  85,  77,  79,  78,  26,
       146,   4, 122,  81,  19, 132,  50,   9, 149,  21, 111,  39,  34,
        46, 113,  60, 105,  69,  86,  84,  47,  16,  95,  31, 127,  59,
        73,  62, 145,  41, 102, 133,  54,   5,  71,  12,  64,  32, 129,
       112, 144,  14, 125,  49,  96,   7])

In [9]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [10]:
test_indexes = shuffled_indexes[:test_size]
train_indexes = shuffled_indexes[test_size:]

In [11]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [12]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [13]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [14]:
from playML.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [16]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [17]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [18]:
from playML.kNN import KNNClassifier

my_knn_clf = KNNClassifier(k=3)
my_knn_clf.fit(X_train, y_train)
y_predict = my_knn_clf.predict(X_test)

In [19]:
y_predict

array([2, 0, 2, 0, 0, 2, 1, 2, 1, 2, 1, 0, 1, 2, 1, 2, 1, 2, 1, 2, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 2])

In [20]:
y_test

array([2, 0, 2, 0, 0, 2, 1, 2, 1, 2, 1, 0, 1, 2, 1, 2, 1, 2, 1, 2, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 2])

In [21]:
sum(y_predict == y_test)

30

In [22]:
sum(y_predict == y_test) / len(y_test)

1.0

### sklearn中的train_test_split

In [23]:
from sklearn.model_selection import train_test_split

train_test_split

<function sklearn.model_selection._split.train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)>

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [25]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [26]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [27]:
from playML.kNN import KNNClassifier

my_knn_clf = KNNClassifier(k=3)
my_knn_clf.fit(X_train, y_train)
y_predict = my_knn_clf.predict(X_test)

In [28]:
sum(y_predict == y_test) / len(y_test)

1.0