## 数据归一化处理

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### 最值归一化 Normalization

In [2]:
x = np.random.randint(0, 100, 100)

In [3]:
x

array([28,  2, 37, 72, 93, 53, 91, 81, 38, 90, 81, 35, 20, 33, 71, 43, 76,
       84, 84,  8, 74, 28, 95, 15, 73,  1, 12, 12,  0, 43, 95, 86, 99, 87,
       59, 77, 76, 33, 11, 17, 56,  3, 16, 94, 50, 36, 51, 88, 46, 28, 23,
       55, 11,  4, 30, 62, 49, 93, 39, 52, 47, 31, 25, 19,  2, 50, 81, 49,
       47, 78, 68, 68,  0,  5,  1, 91, 88, 81, 34, 80, 29, 78, 46, 71, 21,
       59, 27, 56, 26, 25, 39, 78,  7, 54, 31, 30, 97, 55, 26, 65])

In [4]:
(x - np.min(x)) / (np.max(x) -np.min(x))

array([0.28282828, 0.02020202, 0.37373737, 0.72727273, 0.93939394,
       0.53535354, 0.91919192, 0.81818182, 0.38383838, 0.90909091,
       0.81818182, 0.35353535, 0.2020202 , 0.33333333, 0.71717172,
       0.43434343, 0.76767677, 0.84848485, 0.84848485, 0.08080808,
       0.74747475, 0.28282828, 0.95959596, 0.15151515, 0.73737374,
       0.01010101, 0.12121212, 0.12121212, 0.        , 0.43434343,
       0.95959596, 0.86868687, 1.        , 0.87878788, 0.5959596 ,
       0.77777778, 0.76767677, 0.33333333, 0.11111111, 0.17171717,
       0.56565657, 0.03030303, 0.16161616, 0.94949495, 0.50505051,
       0.36363636, 0.51515152, 0.88888889, 0.46464646, 0.28282828,
       0.23232323, 0.55555556, 0.11111111, 0.04040404, 0.3030303 ,
       0.62626263, 0.49494949, 0.93939394, 0.39393939, 0.52525253,
       0.47474747, 0.31313131, 0.25252525, 0.19191919, 0.02020202,
       0.50505051, 0.81818182, 0.49494949, 0.47474747, 0.78787879,
       0.68686869, 0.68686869, 0.        , 0.05050505, 0.01010

In [5]:
X = np.random.randint(0, 100, (50, 2))

In [6]:
X 

array([[62, 68],
       [20, 13],
       [60, 63],
       [49, 57],
       [54, 36],
       [47, 50],
       [16, 96],
       [86, 54],
       [37, 69],
       [63,  0],
       [35,  0],
       [ 6, 83],
       [39, 56],
       [66,  8],
       [67, 40],
       [89, 22],
       [ 1, 24],
       [78, 79],
       [58, 34],
       [43, 24],
       [58, 96],
       [ 3, 57],
       [18, 53],
       [52, 99],
       [61, 51],
       [54, 82],
       [64, 40],
       [ 2, 66],
       [ 0, 62],
       [54, 88],
       [69, 69],
       [54, 20],
       [ 4, 74],
       [18, 84],
       [11, 86],
       [ 9, 90],
       [ 6, 14],
       [65, 91],
       [49, 40],
       [90, 46],
       [40, 85],
       [55, 68],
       [63, 56],
       [17, 10],
       [84, 91],
       [63, 46],
       [68, 42],
       [87, 25],
       [ 9, 75],
       [15, 18]])

In [7]:
X = np.array(X, dtype=float)

In [8]:
X[:10, :] # X数组的前10个元素

array([[62., 68.],
       [20., 13.],
       [60., 63.],
       [49., 57.],
       [54., 36.],
       [47., 50.],
       [16., 96.],
       [86., 54.],
       [37., 69.],
       [63.,  0.]])